local addonName, addon = ...
local Catalog = addon.Catalog
local BASE = "Interface\\AddOns\\" .. addonName .. "\\HUDArtwork\\"

local artwork = {
    {
        key = "Xalatath",
        labelKey = "PLU_DT_ARTWORK_XALATATH",
        label = "Xal'atath",
        order = 1,
        aspectRatio = 1,
        randomEligible = true,
        leftPath = BASE .. "xalatath-left.tga",
        rightPath = BASE .. "xalatath-right.tga",
    },
    {
        key = "Arator",
        labelKey = "PLU_DT_ARTWORK_ARATOR",
        label = "Arator",
        order = 2,
        aspectRatio = 1,
        randomEligible = true,
        leftPath = BASE .. "arator-left.tga",
        rightPath = BASE .. "arator-right.tga",
    },
    {
        key = "Sylvanas",
        labelKey = "PLU_DT_ARTWORK_SYLVANAS",
        label = "Sylvanas",
        order = 3,
        aspectRatio = 1,
        randomEligible = true,
        leftPath = BASE .. "sylvanas-left.tga",
        rightPath = BASE .. "sylvanas-right.tga",
    },
    {
        key = "Arthas",
        labelKey = "PLU_DT_ARTWORK_ARTHAS",
        label = "Arthas",
        order = 4,
        aspectRatio = 1,
        randomEligible = true,
        leftPath = BASE .. "arthas-left.tga",
        rightPath = BASE .. "arthas-right.tga",
    },
    {
        key = "Thrall",
        labelKey = "PLU_DT_ARTWORK_THRALL",
        label = "Thrall",
        order = 5,
        aspectRatio = 1,
        randomEligible = true,
        leftPath = BASE .. "thrall-right.tga",
        rightPath = BASE .. "thrall-left.tga",
    },
    {
        key = "Jaina",
        labelKey = "PLU_DT_ARTWORK_JAINA",
        label = "Jaina",
        order = 6,
        aspectRatio = 1,
        randomEligible = true,
        leftPath = BASE .. "jaina-left.tga",
        rightPath = BASE .. "jaina-right.tga",
    },
    {
        key = "Illidan",
        labelKey = "PLU_DT_ARTWORK_ILLIDAN",
        label = "Illidan",
        order = 7,
        aspectRatio = 1,
        randomEligible = true,
        leftPath = BASE .. "illidan-left.tga",
        rightPath = BASE .. "illidan-right.tga",
    },
    {
        key = "Kaelthas",
        labelKey = "PLU_DT_ARTWORK_KAELTHAS",
        label = "Kael'thas",
        order = 8,
        aspectRatio = 1,
        randomEligible = true,
        leftPath = BASE .. "kaelthas-right.tga",
        rightPath = BASE .. "kaelthas-left.tga",
    },
    {
        key = "Guldan",
        labelKey = "PLU_DT_ARTWORK_GULDAN",
        label = "Gul'dan",
        order = 9,
        aspectRatio = 1,
        randomEligible = true,
        leftPath = BASE .. "guldan-right.tga",
        rightPath = BASE .. "guldan-left.tga",
    },
    {
        key = "NightElf",
        labelKey = "PLU_DT_ARTWORK_NIGHTELF",
        label = "Night Elf",
        order = 10,
        aspectRatio = 1,
        randomEligible = true,
        leftPath = BASE .. "nightelf-left.tga",
        rightPath = BASE .. "nightelf-right.tga",
    },
    {
        key = "DwarfHunter",
        labelKey = "PLU_DT_ARTWORK_DWARFHUNTER",
        label = "Dwarf Hunter",
        order = 11,
        aspectRatio = 1,
        randomEligible = true,
        leftPath = BASE .. "dwarfhunter-left.tga",
        rightPath = BASE .. "dwarfhunter-right.tga",
    },
    {
        key = "ForsakenWarlock",
        labelKey = "PLU_DT_ARTWORK_FORSAKENWARLOCK",
        label = "Forsaken Warlock",
        order = 12,
        aspectRatio = 1,
        randomEligible = true,
        leftPath = BASE .. "forsakenwarlock-left.tga",
        rightPath = BASE .. "forsakenwarlock-right.tga",
    },
    {
        key = "Tauren",
        labelKey = "PLU_DT_ARTWORK_TAUREN",
        label = "Tauren",
        order = 13,
        aspectRatio = 1,
        randomEligible = true,
        leftPath = BASE .. "tauren-left.tga",
        rightPath = BASE .. "tauren-right.tga",
    },
    {
        key = "Alexstrasza",
        labelKey = "PLU_DT_ARTWORK_ALEXSTRASZA",
        label = "Alexstrasza",
        order = 14,
        aspectRatio = 1,
        randomEligible = true,
        leftPath = BASE .. "alexstrasza-left.tga",
        rightPath = BASE .. "alexstrasza-right.tga",
    },
}

Catalog:Register("hud-artwork", artwork)
